version: '3.8'

services:
  backend:
    build:
      context: ./nestjs-text-summarization
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - GOOGLE_GEMINI_MODEL=${GOOGLE_GEMINI_MODEL}
      - MODEL_TYPE=${MODEL_TYPE}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL={GROQ_MODEL}
    ports:
      - "${PORT}:${PORT}"
    # depends_on:
    #   - ollama
    #   - ollama-webui
    networks:
      - ai
    restart: unless-stopped
  web:
    build:
      context: ./ng-text-summarization-app
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - ai
    restart: unless-stopped
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - ${OLLAMA_PORT}:${OLLAMA_PORT}
  #   volumes:
  #     - .:/code
  #     - ./ollama/ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: always
  #   networks:
  #     - ai
  # ollama-webui:
  #   image: ghcr.io/ollama-webui/ollama-webui:main
  #   container_name: ollama-webui
  #   volumes:
  #     - ./ollama/ollama-webui:/app/backend/data
  #   depends_on:
  #     - ollama
  #   ports:
  #     - ${OLLAMA_WEB_PORT}:${OLLAMA_WEB_PORT}
  #   environment:
  #     - '/ollama/api=${OLLAMA_BASE_URL}/api'
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   restart: unless-stopped
  #   networks:
  #     - ai
networks:
  ai: